### ISSUE TITLE
EHN: improve whitematteranalysis wiki

### ISSUE THREAD

**Issue by zhangfanmark** [SlicerDMRI/whitematteranalysis#50]
- The wm_registermultisubject_faster.py instructions say that it is typically run using **control data** which may be not.   -- Maybe add other possibilities, e.g. random sampling from whole dataset. 

- Maybe add a few sentences after the section title to give an overview. 

- Maybe add Step 1, Step 1.1, Step 2, etc. to show the pipeline is ran step-by-step.

- Maybe emphasize (bold? italic?) the first sentence under each script, which is the description of the script.

**Comment by nsomes** [comment]
- Maybe clarify the difference between the remove outliers script and the remove outliers folder that is generated automatically by the wm_cluster_atlas.py

- The example under wm_harden_transform.py refers to wm_extract_cluster.py instead.

- Maybe change the recommended range for pthresh in the wm_separate_clusters_by_hemisphere help because it seems like values outside of that range are common to use.

**Comment by nsomes** [comment]
- Maybe move the wm_harden_transform.py script description to being outside of the endpoint analysis section, since it is often necessary even when you are not running endpoint analysis.

-Maybe add a bit more for wm_harden_transform.py about the purpose of the script and how essential it is to do so that it is comparable to other files in dwi space.

**Comment by ljod** [comment]
Thanks everyone. This issue is closed and remaining items are integrated into a new summary issue.
